name: chimera-gpu-e1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  train_matrix:
    runs-on: [self-hosted, linux, x64, gpu]
    strategy:
      fail-fast: false
      matrix:
        model: [unet_small, fractal_unet_small]
        seed: [0, 1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Parity gate preflight
        if: ${{ matrix.model == 'unet_small' && matrix.seed == 0 }}
        run: |
          python scripts/assert_param_flops_torch.py             --fractal configs/models/fractal_unet_small.yaml             --baseline configs/models/unet_small.yaml             --tol 0.05
      - name: Train E1 (IND)
        env: { CUDA_VISIBLE_DEVICES: "0" }
        run: |
          python run_hydra.py model=${{ matrix.model }} data=cfd2d_ind_v1 experiment=E1_cfd2d dry_run=false seeds_override=[${{ matrix.seed }}]
      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chimera-${{ matrix.model }}-seed${{ matrix.seed }}
          path: artifacts/E1/${{ (matrix.model == 'unet_small' && 'UNetSmall') || 'FractalUNetSmall' }}_seed${{ matrix.seed }}/

  aggregate:
    runs-on: ubuntu-latest
    needs: [train_matrix]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts_downloaded
      - name: Collate to artifacts/E1
        run: |
          mkdir -p artifacts/E1
          find artifacts_downloaded -type f -name "metrics.json" -exec bash -c 'dest="artifacts/E1/$(basename $(dirname "$1"))"; mkdir -p "$dest"; cp "$1" "$dest/metrics.json"' _ {} \;
      - name: Aggregate & stats
        run: |
          python scripts/collect_metrics.py --root artifacts/E1 --out artifacts/E1_summary.json
          python eval/compute_stats.py --in artifacts/E1_summary.json --out artifacts/E1_results.json
          python eval/generate_plots_stub.py --summary artifacts/E1_summary.json --out artifacts/fig1_ind_ood.png
      - name: Upload summary & figures
        uses: actions/upload-artifact@v4
        with:
          name: chimera-e1-summary
          path: |
            artifacts/E1_summary.json
            artifacts/E1_results.json
            artifacts/fig1_ind_ood.png
